### ISSUE TITLE
How to use this library with bazel ?

### ISSUE THREAD

**Issue by srilakshmikanthanp** [segmentio/kafka-go#1082]
I have created the WORKSPACE.bazel like this,

~~~bazel
# Load the git_respository function
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

# load the http_archive function
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# load the go rules and toolchains
http_archive(
  urls = [
    "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
    "https://github.com/bazelbuild/rules_go/releases/download/v0.37.0/rules_go-v0.37.0.zip",
  ],
  name = "io_bazel_rules_go",
  sha256 = "56d8c5a5c91e1af73eca71a6fab2ced959b67c86d12ba37feedb0a2dfea441a6",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains(version = "1.19.3")

# Some more libraries


# load kafka-go library
new_git_repository(
  build_file="//@thirdparty:kafka-go/kafka-go.BUILD.bazel",
  name="kafka-go",
  remote="https://github.com/segmentio/kafka-go.git",
  tag="v0.4.38",
)

~~~

kafka-go.BUILD.bazel like this,

~~~bazel
"""
Build file for kafka-go
"""

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
  visibility = ["//visibility:public"],
  name = "kafka-go",
  srcs = glob(["**/*.go"]),
  importpath = "github.com/segmentio/kafka-go",
)
~~~

And in some binary like this,

~~~bazel
"""
Build filr for patcher
"""

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_path")

go_path(
  name = "gopath",
  mode ="link",
  deps = [
    "@kafka-go//:kafka-go",
    "@ftp-go//:ftp-go",
    "//library-go:library-go",
  ]
)

go_binary(
  srcs = glob(["*.go"]),
  name = "patcher",
  deps = [
    "@kafka-go//:kafka-go",
    "@ftp-go//:ftp-go",
    "//library-go:library-go",
  ]
)

~~~

if I run bazel build `bazel build //patcher:gopath` error comes like this,

~~~sh
DEBUG: Rule 'kafka-go' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "a8e74f3adaeac13314ff6d06f15f1d47693b287d", shallow_since = "1667956384 -0800" and dropping ["tag"]
DEBUG: Repository kafka-go instantiated at:
  /home/goodwilludp/Documents/source/live-udp/WORKSPACE.bazel:44:19: in <toplevel>
Repository rule git_repository defined at:
  /home/goodwilludp/.cache/bazel/_bazel_goodwilludp/137afe0e20a54c7d333aaa6294979500/external/bazel_tools/tools/build_defs/repo/git.bzl:176:33: in <toplevel>
ERROR: /home/goodwilludp/Documents/source/live-udp/patcher/BUILD.bazel:7:8: in go_path rule //patcher:gopath: 
Traceback (most recent call last):
        File "/home/goodwilludp/.cache/bazel/_bazel_goodwilludp/137afe0e20a54c7d333aaa6294979500/external/io_bazel_rules_go/go/private/tools/path.bzl", line 82, column 32, in _go_path_impl
                _add_manifest_entry(manifest_entries, manifest_entry_map, inputs, f, dst)
        File "/home/goodwilludp/.cache/bazel/_bazel_goodwilludp/137afe0e20a54c7d333aaa6294979500/external/io_bazel_rules_go/go/private/tools/path.bzl", line 273, column 17, in _add_manifest_entry
                fail("{}: references multiple files ({} and {})".format(dst, entry_map[dst], src.path))
Error in fail: src/github.com/segmentio/kafka-go/snappy.go: references multiple files (external/kafka-go/compress/snappy/go-xerial-snappy/snappy.go and external/kafka-go/compress/snappy/snappy.go)
ERROR: /home/goodwilludp/Documents/source/live-udp/patcher/BUILD.bazel:7:8: Analysis of target '//patcher:gopath' failed
ERROR: Analysis of target '//patcher:gopath' failed; build aborted: 
INFO: Elapsed time: 3.646s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 607 targets configured)
~~~

How to fix this ?

**Comment by dominicbarnes** [comment]
I've never used bazel before, but this sounds more like an issue on that side rather than ours. Sorry, but I don't know what this error means or how to address it.
