### ISSUE TITLE
Kafka cluster unavailable cause close the async writer blocked for a long time

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#1099]
**Describe the bug**

> one kafka server, writer in the async mode, send a huge number of messages, `kill -9` kafka server to mock the electricity lost scenario.

after the kafka server is killed, it becomes available, so that send messages failed, report the error, try to close the writer by call `Writer.Close()` method, this is blocked for a long time, more than a few minutes, and don't when it should returned.

**Kafka Version**

> * What version(s) of Kafka are you testing against? 

confluent-7.3.2

> * What version of kafka-go are you using?

v0.4.39-0.20230217181906-f6986fb02ee7

**To Reproduce**

> Resources to reproduce the behavior:

```yaml
---
# docker-compose.yaml
#
# Adding a docker-compose file will help the maintainers setup the environment
# to reproduce the issue.
#
# If one the docker-compose files available in the repository may be used,
# mentioning it is also a useful alternative.
...
```

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
    // Adding a fully reproducible example will help maintainers provide
    // assistance to debug the issues.
    ...
}
```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

close the writer in the async mode should return as soon as possible, do not block the application.

**Observed Behavior**

> A clear and concise description of the behavior you observed.

clos the writer blocked for a long time.

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.

We found that one goroutine named `writeBatch` is sleep

**Comment by 3AceShowHand** [comment]
```
goroutine 421 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0x14003641440?)
	runtime/sema.go:62 +0x2c
sync.(*WaitGroup).Wait(0x1400354b088)
	sync/waitgroup.go:116 +0x74
github.com/segmentio/kafka-go.(*Writer).Close(0x1400354afc0)
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/writer.go:571 +0x14c
github.com/pingcap/tiflow/pkg/sink/kafka/v2.(*asyncWriter).Close(0x1400354c500)
	github.com/pingcap/tiflow/pkg/sink/kafka/v2/factory.go:332 +0x44
github.com/pingcap/tiflow/cdc/sink/dmlsink/mq/dmlproducer.(*kafkaDMLProducer).Close(0x1400081a460)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go:154 +0x1ec
github.com/pingcap/tiflow/cdc/sink/dmlsink/mq.(*worker).close(0x14002d7f440)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/mq/worker.go:315 +0xbc
github.com/pingcap/tiflow/cdc/sink/dmlsink/mq.(*dmlSink).Close(0x1400081a540)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/mq/mq_dml_sink.go:149 +0x40
github.com/pingcap/tiflow/cdc/sink/dmlsink/factory.(*SinkFactory).Close(0x14002ca3b60)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/factory/factory.go:134 +0x64
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).Close(0x140035363c0)
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:898 +0x3e8
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0x1400184a420, {0x104ded450, 0x1405d29d158})
	github.com/pingcap/tiflow/cdc/processor/processor.go:948 +0x334
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0x140006241e0, {{0x14000ac2d12, 0x7}, {0x14000ac2d2a, 0xa}}, {0x104ded450, 0x1405d29d158})
	github.com/pingcap/tiflow/cdc/processor/manager.go:166 +0x7c
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0x140006241e0, {0x12ef32c98?, 0x140017d80a0}, {0x104dbc798?, 0x140010423c0})
	github.com/pingcap/tiflow/cdc/processor/manager.go:144 +0x410
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0x14000de0d10, {0x12ef32c98, 0x140017d80a0}, 0x14001036600, 0x2faf080, {0x1039b1e0a, 0x9})
	github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0xbb4
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0x14000820460, {0x104ded4f0?, 0x140017d80a0}, {0x12ed4b6f8, 0x140006241e0}, {0x104dbc798, 0x140010423c0}, 0x0?, {0x1039b1e0a, 0x9})
	github.com/pingcap/tiflow/cdc/capture/capture.go:500 +0x110
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4()
	github.com/pingcap/tiflow/cdc/capture/capture.go:342 +0x234
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x9c


goroutine 714 [select]:
github.com/segmentio/kafka-go.(*connPool).discover(0x14002d46840, {0x104dd5a88, 0x140007acc30}, 0x14002d56e40)
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/transport.go:620 +0x334
created by github.com/segmentio/kafka-go.(*Transport).grabPool
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/transport.go:254 +0x59c

goroutine 944 [select, 2 minutes]:
github.com/segmentio/kafka-go.(*connPool).discover(0x14002cc5140, {0x104dd5a88, 0x140036a70e0}, 0x140037f0000)
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/transport.go:620 +0x334
created by github.com/segmentio/kafka-go.(*Transport).grabPool
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/transport.go:254 +0x59c


goroutine 863 [sleep]:
time.Sleep(0x3b9aca00)
	runtime/time.go:195 +0x114
github.com/segmentio/kafka-go.(*partitionWriter).writeBatch(0x14002f05aa0, 0x140089d49a0)
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/writer.go:1119 +0x2f0
github.com/segmentio/kafka-go.(*partitionWriter).writeBatches(0x14002f05aa0)
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/writer.go:1016 +0x2c
github.com/segmentio/kafka-go.(*Writer).spawn.func1()
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/writer.go:545 +0x5c
created by github.com/segmentio/kafka-go.(*Writer).spawn
	github.com/segmentio/kafka-go@v0.4.39-0.20230217181906-f6986fb02ee7/writer.go:543 +0x88

```

**Comment by 3AceShowHand** [comment]
After the Kafka server is unavailable, it's impossible to send messages to the cluster, so there is no need to waste too much time on it, return as soon as possible is reasonable.

How about add a new option named boolean `ForceClose` to the `Writer`, if it's true, close the writer immediately.

**Comment by 3AceShowHand** [comment]
@achille-roussel @nlsun Please take a look at this issue, I think this is a very critical problem need to be resolved.

**Comment by rhansen2** [comment]
I believe this is expected behavior. Close() Waits for pending batches to be written before returning. Since the cluster has gone away I suspect it could take a while for all batches to retry and eventually fail.
