### ISSUE TITLE
Fail to produce messages using kafka Golang using SASL and SCRAM 256 authentication

### ISSUE THREAD

**Issue by acharbha** [segmentio/kafka-go#1190]
**Fail to produce messages using kafka Golang using SASL and SCRAM 256 authentication**

> A clear and concise description of what the bug is.
Fail to produce messages using kafka Golang using SASL and SCRAM 256 authentication

**Kafka Version**

> * What version(s) of Kafka are you testing against?
3.5.1
> * What version of kafka-go are you using?
v0.4.4

**To Reproduce**
```go
package main

import (
	"fmt"
	"log"
	"time"

	"context"

	"github.com/segmentio/kafka-go"
	"github.com/segmentio/kafka-go/sasl/scram"
)

func main() {
	saslUsername := "admin"
	saslPassword := "admin"
	brokerList := "Ip1:9094,Ip2:9094,Ip3:9094"
	topic := "my-topic"

	scram, err := scram.Mechanism(scram.SHA256, saslUsername, saslPassword)
	if err != nil {
		log.Fatalf("Failed to create SCRAM mechanism: %v", err)
	}

	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: scram,
	}

	writer := kafka.NewWriter(kafka.WriterConfig{
		Brokers:  []string{brokerList},
		Topic:    topic,
		Balancer: &kafka.Hash{},
		Dialer:   dialer,
	})

	defer writer.Close()

	// Add your Kafka message production logic here

	// Example:
	message := kafka.Message{
		Key:   []byte("key"),
		Value: []byte("Hello, Kafka!"),
	}

	ctx := context.Background()
	err = writer.WriteMessages(ctx, message) // Pass the context as the first argument
	if err != nil {
		log.Fatalf("Failed to write message: %v", err)
	}

	fmt.Println("Message sent successfully")
}

```

**Expected Behavior**

> A clear and concise description of what you expected to happen.
not able to produce the messages as expected.

**Observed Behavior**

> A clear and concise description of the behavior you observed.
```shell
go run .\produce.go
panic: runtime error: index out of range [2] with length 1

goroutine 7 [running]:
github.com/segmentio/kafka-go.(*connGroup).connect.func1(0xc000022bd0?, 0xc000000003?)
        C:/Users/acharbha/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.4/transport.go:994 +0x137
math/rand.(*Rand).Shuffle(0x3?, 0x2b?, 0xc00005be58)
        C:/Program Files/Go/src/math/rand/rand.go:265 +0x8b
math/rand.Shuffle(0xc000014340?, 0x3f?)
        C:/Program Files/Go/src/math/rand/rand.go:470 +0x2c
github.com/segmentio/kafka-go.(*connGroup).connect(0xc00016b9c0, {0xe37cf8, 0xc000064190})
        C:/Users/acharbha/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.4/transport.go:993 +0x1ef
github.com/segmentio/kafka-go.(*connGroup).grabConnOrConnect.func1()
        C:/Users/acharbha/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.4/transport.go:883 +0x5b
created by github.com/segmentio/kafka-go.(*connGroup).grabConnOrConnect in goroutine 6
        C:/Users/acharbha/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.4/transport.go:882 +0x105
exit status 2
```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.
Please let me know if there way we can develop kafka producer app using Golang with SASL auth & SCRAM 256 mechanism.

**Comment by petedannemann** [comment]
I think this error may actually be coming from the use of a comma delimited list of brokers, not a SASL issue.

Could you try changing this
```go
brokerList := "Ip1:9094,Ip2:9094,Ip3:9094"
...
    Brokers:  []string{brokerList},
```
to something like:
```go
brokerList := []string{"Ip1:9094", "Ip2:9094", "Ip3:9094"}
...
    Brokers:  brokerList,
```

**Comment by petedannemann** [comment]
The error is [here](https://github.com/segmentio/kafka-go/blob/f4ca0b48296538eb5639027cd83f40a3828caf7d/transport.go#L994) when kafka-go tries to parse the address provided, which doesn't support a comma delimited list

**Comment by acharbha** [comment]
thanks now getting a different error:

```shell
go run .\produce.go
2023/09/05 19:33:27 Failed to write message: unexpected EOF
exit status 1
```

**Comment by petedannemann** [comment]
`unexpected EOF` can option come up when the cluster expects TLS but that isn't configured in your client code. We have some brief documentation on this issue [here](https://github.com/segmentio/kafka-go#tls-support).

Do you know if your kafka cluster is configured to use TLS? If so you will need to configure that on your client

**Comment by petedannemann** [comment]
`v0.4.4` is quite old and there have been several TLS bug fixes since then ([this one might be applicable?](https://github.com/segmentio/kafka-go/releases/tag/v0.4.30). Can you try upgrading to a recent release?

**Comment by petedannemann** [comment]
Hi @acharbha have you had a chance to try my suggestion?

**Comment by acharbha** [comment]
@petedannemann sorry I had to discontinue testing with Golang as I found Golang for Kafka tedious for me.
