### ISSUE TITLE
Error getting request for apiKey: 11 and apiVersion: 1

### ISSUE THREAD

**Issue by XiaochenCui** [segmentio/kafka-go#156]
Error occurring during consume from kafka cluster

Consumer code:
```
func main() {
	kafkaBrokerUrl := "localhost:19092,localhost:29092,localhost:39092"
	brokers := strings.Split(kafkaBrokerUrl, ",")

	kafkaTopic := "test"
	kafkaClientId := "comsumer-group-test"

	// make a new reader that consumes from topic-A
	config := kafka.ReaderConfig{
		Brokers:  brokers,
		GroupID:  kafkaClientId,
		Topic:    kafkaTopic,
		MinBytes: 10e3, //10KB
		MaxBytes: 10e6, //10MB
	}

	reader := kafka.NewReader(config)
	defer reader.Close()

	for {
		m, err := reader.ReadMessage(context.Background())
		if err != nil {
			log.Errorf("error while receiving message: %s", err.Error())
			break
		}

		log.Printf("message at topic/partition/offset %v/%v/%v: %s\n", m.Topic,
			m.Partition, m.Offset, string(m.Value))
	}
}
```

Kafka log:
```
kafka-1_1_484e7e5b9515 | [2018-12-07 03:10:26,527] ERROR Closing socket for 172.25.0.6:19092-172.25.0.1:54624 because of error (kafka.network.Processor)
kafka-1_1_484e7e5b9515 | kafka.network.InvalidRequestException: Error getting request for apiKey: 11 and apiVersion: 1
kafka-1_1_484e7e5b9515 |        at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:95)
kafka-1_1_484e7e5b9515 |        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:87)
kafka-1_1_484e7e5b9515 |        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:488)
kafka-1_1_484e7e5b9515 |        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:483)
kafka-1_1_484e7e5b9515 |        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
kafka-1_1_484e7e5b9515 |        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
kafka-1_1_484e7e5b9515 |        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
kafka-1_1_484e7e5b9515 |        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
kafka-1_1_484e7e5b9515 |        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:483)
kafka-1_1_484e7e5b9515 |        at kafka.network.Processor.run(SocketServer.scala:413)
kafka-1_1_484e7e5b9515 |        at java.lang.Thread.run(Thread.java:745)
kafka-1_1_484e7e5b9515 | Caused by: java.lang.IllegalArgumentException: Invalid version for API key 11: 1
kafka-1_1_484e7e5b9515 |        at org.apache.kafka.common.protocol.ProtoUtils.schemaFor(ProtoUtils.java:31)
kafka-1_1_484e7e5b9515 |        at org.apache.kafka.common.protocol.ProtoUtils.requestSchema(ProtoUtils.java:44)
kafka-1_1_484e7e5b9515 |        at org.apache.kafka.common.protocol.ProtoUtils.parseRequest(ProtoUtils.java:60)
kafka-1_1_484e7e5b9515 |        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:144)
kafka-1_1_484e7e5b9515 |        at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:56)
kafka-1_1_484e7e5b9515 |        at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:92)
kafka-1_1_484e7e5b9515 |        ... 10 more
```

**Comment by achille-roussel** [comment]
Could you share the version of Kafka that you are testing against?

**Comment by stevevls** [comment]
The logs would indicate Kafka 1.1, but it shouldn't be complaining about that version of the `JoinGroupRequest` (api key 11).  Our CI tests cover that combination.  Going to close for now due to inactivity.

**Comment by Erog38** [comment]
I just ran into this as well. Kafka 2.1.1 with this docker-compose.yml

[docker-compose.yml](https://github.com/segmentio/kafka-go/files/2903015/docker-compose.yml.txt)

**Comment by stevevls** [comment]
Hi @Erog38.  It looks like the docker setup you posted is using Confluent Platform 3.0.1, which runs Kafka 0.10.0.1 (https://docs.confluent.io/3.0.1/release-notes.html).  We're using `JoinGroupRequest` `v1`, which was added in Kafka 0.10.1.0.  We should be able to downgrade the request to `v0` when connecting to older versions.

**Comment by Erog38** [comment]
@stevevls Thanks for the info! I'll upgrade to 0.10.1.0 soon and play around with it there, but this support would be greatly appreciated.

**Comment by stevevls** [comment]
Sounds good.  In other news, we just added an official list of supported Kafka versions (#217).

**Comment by stevevls** [comment]
We're going to close this issue for now since the documentation has been updated and we now list officially supported versions.
