### ISSUE TITLE
AsyncProducer: runtime: out of memory(OOM)

### ISSUE THREAD

**Issue by qiangmzsx** [segmentio/kafka-go#273]
**Describe the bug**
The OOM appears when AsyncProducer writes a lot of messages.

**Kafka Version**
1.1.0

**To Reproduce**
matser
**Expected behavior**

**Additional context**
```
ERROR: logging before flag.Parse: I0512 20:14:04.725666   15813 statistics.go:219] producter =2550000
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x64d147, 0x16)
        /export/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc4585e0000, 0x100000, 0x786b00, 0x79fb58)
        /export/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x786b00, 0x100000, 0x7fb294fd97c0)
        /export/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x786b00, 0x1, 0x0)
        /export/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x786b00, 0x1, 0x79fb68, 0x7fb294fd97c0)
        /export/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x786b00, 0x1, 0xc420000002, 0x7fb294fd97c0)
        /export/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /export/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x786b00, 0x1, 0x7fb294010002, 0x7fb294fd97c0)
        /export/go/src/runtime/mheap.go:752 +0x8a
runtime.(*mcentral).grow(0x787ed0, 0x0)
        /export/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x787ed0, 0x7fb294fd97c0)
        /export/go/src/runtime/mcentral.go:106 +0x2e4
runtime.(*mcache).refill(0x7fb32d620000, 0xc420045602)
        /export/go/src/runtime/mcache.go:123 +0x9c
runtime.(*mcache).nextFree.func1()
        /export/go/src/runtime/malloc.go:556 +0x32
runtime.systemstack(0x0)
        /export/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /export/go/src/runtime/proc.go:1175

goroutine 29 [running]:
runtime.systemstack_switch()
        /export/go/src/runtime/asm_amd64.s:363 fp=0xc420045c50 sp=0xc420045c48 pc=0x453280
runtime.(*mcache).nextFree(0x7fb32d620000, 0x2, 0x30, 0x613d20, 0x63e680)
        /export/go/src/runtime/malloc.go:555 +0xa9 fp=0xc420045ca8 sp=0xc420045c50 pc=0x410b49
runtime.mallocgc(0x8, 0x5f5640, 0x1, 0xc4585cbc80)
        /export/go/src/runtime/malloc.go:710 +0x79f fp=0xc420045d48 sp=0xc420045ca8 pc=0x41149f
runtime.newobject(0x5f5640, 0xc4585cbc80)
        /export/go/src/runtime/malloc.go:839 +0x38 fp=0xc420045d78 sp=0xc420045d48 pc=0x411848
main.NewKafkaProducter_Sync_time()
        /export/data/gopath/src/gitlab.xxxxxxx.com/zeroteam/ddkafka/examples/statistics.go:211 +0x50f fp=0xc420045fe0 sp=0xc420045d78 pc=0x5ca87f
runtime.goexit()
        /export/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420045fe8 sp=0xc420045fe0 pc=0x455dd1
created by main.main
        /export/data/gopath/src/gitlab.xxxxxxx.com/zeroteam/ddkafka/examples/statistics.go:63 +0x14d
```

**Comment by achille-roussel** [comment]
Hello @qiangmzsx, thanks for reporting the issue.

Would you be able to provide more details about your setup? For example:
- memory available to the process
- rate of messages produced
- size of the messages (min, avg, max)
- how long was the producer running for before it ran out of memory
- were the kafka broker experiencing issues during that time?

If we are able to capture memory profiles that would be extremely useful as well to understand where memory is being retained.
