### ISSUE TITLE
panic on writing on a high load situation

### ISSUE THREAD

**Issue by josledp** [segmentio/kafka-go#37]
Hi,
  trying to put preassure to kafka we had a panic using kafka-go:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x522d32]

goroutine 2824 [running]:
[...]/vendor/github.com/segmentio/kafka-go.(*Conn).Close(0x0, 0x0, 0xc420c538b0)
	[...]/vendor/github.com/segmentio/kafka-go/conn.go:135 +0x22
[...]/vendor/github.com/segmentio/kafka-go.(*writer).run(0xc420c1d110)
	[...]/vendor/github.com/segmentio/kafka-go/writer.go:475 +0x6d0
created by [...]/vendor/github.com/segmentio/kafka-go.newWriter
	[...]/vendor/github.com/segmentio/kafka-go/writer.go:418 +0x143
```

it seems the problem is here:
```
                       if conn, err = w.write(conn, batch, resch); err != nil {
                                conn.Close()
                                conn = nil
                        }
``` 

because w.write can return nil and an error, and it tries to close the conn without validating if its nil.

**Comment by achille-roussel** [comment]
Thanks for reporting, I can tackle this sometimes tomorrow, or if you send a fix we merge it earlier.
