### ISSUE TITLE
Sending message to Kafka caused Java ERROR

### ISSUE THREAD

**Issue by northfun** [segmentio/kafka-go#611]
**Describe the bug**

**We have system using both Java and Go.When java consumed the message sent by go, error occurred.**

Kafka message sent well, go programs can consume the message sent by go, java can consume the message sent by java, but java consumer stoped when consuming the  go message from Kafka.

sdk version:
segmentio/kafka-go v0.4.10
jdk version:
openjdk:8u201

**Kafka Version**
What version(s) of Kafka are you testing against?
Kafka 2.2

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.
```
	config := kafka.WriterConfig{
		Brokers:          wp.urls,
		Topic:            topic,
		Balancer:         &kafka.LeastBytes{},
		Dialer:           wp.dialer,
		WriteTimeout:     TIMEOUT,
		ReadTimeout:      TIMEOUT,
		CompressionCodec: snappy.NewCompressionCodec(),
		Logger: kafka.LoggerFunc(func(format string, args ...interface{}) {
			logger.Warn(fmt.Sprintf("[kafka2], "+format, args...))
		}),
		ErrorLogger: kafka.LoggerFunc(func(format string, args ...interface{}) {
			logger.Warn(fmt.Sprintf("[kafka2],"+format, args...))
		}),
	}

	writer := kafka.NewWriter(config)
	defer func() {
		err = writer.Close()
	}()

	writer.WriteMessages(ctx, kafka.Message{
		Key:   key,
		Value: value,
		Time:  time.Now(),
	})
```
**Expected behavior**
Java can consume the message sent by go.

**Additional context**

When java consumed the message sent by go, error occurred:
```
2021-03-04 13:28:56.877 ERROR 1 --- [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : Error while stopping the container:

java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-0c0e04ee-310a-48e3-9504-bad259bbf5a4-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-0c0e04ee-310a-48e3-9504-bad259bbf5a4-libsnappyjava.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
        at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
        at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
        at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
        at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:168)
        at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:292)
        at org.apache.kafka.common.record.DefaultRecordBatch$1.readNext(DefaultRecordBatch.java:264)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:563)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:532)
        at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.nextFetchedRecord(Fetcher.java:1183)
        at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1218)
        at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:1072)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:562)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:523)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1259)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:741)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:698)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
``` 
And Java listener on Kafka stoped.

**Comment by stevevls** [comment]
Hi @northfun.  It looks like your java consumer is unable to load a native library required to decode messages that have been compressed with Snappy.  Your options are to change or disable compression in your kafka-go `WriterConfig` or to install the native library for snappy on the java side.  Good luck!

**Comment by northfun** [comment]
> Hi @northfun. It looks like your java consumer is unable to load a native library required to decode messages that have been compressed with Snappy. Your options are to change or disable compression in your kafka-go `WriterConfig` or to install the native library for snappy on the java side. Good luck!

Thanks for your advise so much, we tried installing missing packages then worked well.
Sorry for such hasty issue.

**Comment by stevevls** [comment]
No worries.  Glad it's working for you now. 😄
