### ISSUE TITLE
Getting EOF while calling CreateTopics in MSK 

### ISSUE THREAD

**Issue by priyank-fuel** [segmentio/kafka-go#899]
**Describe the bug**

> I am writing a golang based client to create topic in my MSK cluster. I am also listing the topics, the create topic is failing with EOF

```
ERRO[0048] EOF                                          
2022/04/26 14:23:33 http: panic serving 127.0.0.1:38046: EOF
goroutine 63 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x88bc40, 0xc0004997b0})
        /usr/local/go/src/runtime/panic.go:844 +0x258
kafka-configurator/m/internal/service.createTopic({0xc0001447e0, 0x47}, {{0x9171de?, 0x1?}, 0x0?, 0x1?})
        /app/internal/service/kafka-config.go:92 +0x674
kafka-configurator/m/internal/service.CreateKafkaTopic.func1({0xb240b8, 0xc0001635e0}, 0xc0001a4ea0?)
        /app/internal/service/kafka-config.go:140 +0x505
net/http.HandlerFunc.ServeHTTP(0xc0003c2800?, {0xb240b8?, 0xc0001635e0?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003a8000, {0xb240b8, 0xc0001635e0}, 0xc0003c2400)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xb23178?}, {0xb240b8, 0xc0001635e0}, 0xc0003c2400)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000191c20, {0xb243a0, 0xc0003a65d0})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Kafka Version**

> Kafka version MSK 2.6.2
> Go API version v0.4.31

**To Reproduce**

> Resources to reproduce the behavior:

```yaml
---
# docker-compose.yaml
#
# Adding a docker-compose file will help the maintainers setup the environment
# to reproduce the issue.
#
# If one the docker-compose files available in the repository may be used,
# mentioning it is also a useful alternative.
...
```
Sample code 
```

session, sessErr := session.NewSession(&aws.Config{
		Region: awsRegion,
	})
	if sessErr != nil {
		logrus.Fatal(sessErr)
	}

	kafkaDialer := &kafka.Dialer{
		Timeout:   (time.Duration(300) * time.Second),
		DualStack: true,
		SASLMechanism: &aws_msk_iam.Mechanism{
			Signer: sigv4.NewSigner(session.Config.Credentials),
			Region: *awsRegion,
		},
		TLS: &tls.Config{},
	}

	conn, err := kafkaDialer.DialContext(context.Background(), "tcp", kafkaURL)
	if err != nil {
		logrus.Error(err)
		panic(err.Error())

	}

	controller, err := conn.Controller()
	if err != nil {
		logrus.Error(err)
		panic(err.Error())

	}

	var controllerConn *kafka.Conn
	controllerConn, err = kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	if err != nil {
		logrus.Error(err)
		panic(err.Error())

	}
	defer controllerConn.Close()

	// topicConfigs := []kafka.TopicConfig{
	// 	{
	// 		Topic:             "sometopic",
	// 		NumPartitions:     1,
	// 		ReplicationFactor: 1,
	// 	},
	// }

	topicConfigs1 := []kafka.TopicConfig{{
		Topic:             "sometopic",
		NumPartitions:     1,
		ReplicationFactor: 1},
	}

	err = controllerConn.CreateTopics(topicConfigs1...)
	if err != nil {
		logrus.Error(err)
		panic(err.Error())

	}
	defer conn.Close()

```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

**Observed Behavior**

> A clear and concise description of the behavior you observed.

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.

**Comment by dr-dro** [comment]
```go
controllerConn, err = kafkaDialer.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
```
kafkaDialer instead of kafka

**Comment by priyank-fuel** [comment]
I am using kafkadialer as my MSK cluster is authenticated by IAM, and I am creating dialer with SASL mechanism  



```
kafkaDialer := &kafka.Dialer{
		Timeout:   (time.Duration(300) * time.Second),
		DualStack: true,
		SASLMechanism: &aws_msk_iam.Mechanism{
			Signer: sigv4.NewSigner(session.Config.Credentials),
			Region: *awsRegion,
		},
		TLS: &tls.Config{},
	}
	```

**Comment by priyank-fuel** [comment]
Thank you so much, I got the issue @dr-dro you were right

This was the issue
```
controllerConn, err = kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
```
Using kafkadialer insted kafka fixed my issue.

**Comment by priyank-fuel** [comment]
Please close the bug.
