### ISSUE TITLE
panic: inconsistent poll.fdMutex

### ISSUE THREAD

**Issue by eeliu** [segmentio/kafka-go#935]
**Describe the bug**

I got panic after application run for hours when loading test.

**Kafka Version**

> * What version(s) of Kafka are you testing against?

kafka-go@v0.4.31

```
goroutine 3360544 [running]:
panic(0xaebbc0, 0xcb2920)
	/usr/local/go/src/runtime/panic.go:1065 +0x565 fp=0xc002a7b628 sp=0xc002a7b560 pc=0x43a825
internal/poll.(*fdMutex).rwunlock(0xc001396580, 0x1, 0xc000d08000)
	/usr/local/go/src/internal/poll/fd_mutex.go:179 +0x112 fp=0xc002a7b650 sp=0xc002a7b628 pc=0x4d9c52
internal/poll.(*FD).readUnlock(0xc001396580)
	/usr/local/go/src/internal/poll/fd_mutex.go:231 +0x32 fp=0xc002a7b678 sp=0xc002a7b650 pc=0x4d9d52
internal/poll.(*FD).Read(0xc001396580, 0xc000d08000, 0x1000, 0x1000, 0x4e5, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:172 +0x23c fp=0xc002a7b6e8 sp=0xc002a7b678 pc=0x4db23c
net.(*netFD).Read(0xc001396580, 0xc000d08000, 0x1000, 0x1000, 0x0, 0x2540bb527, 0x3d)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f fp=0xc002a7b748 sp=0xc002a7b6e8 pc=0x54406f
net.(*conn).Read(0xc001960010, 0xc000d08000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91 fp=0xc002a7b7b0 sp=0xc002a7b748 pc=0x5561b1
bufio.(*Reader).fill(0xc0021f63f0)
	/usr/local/go/src/bufio/bufio.go:101 +0x108 fp=0xc002a7b800 sp=0xc002a7b7b0 pc=0x570d48
bufio.(*Reader).Peek(0xc0021f63f0, 0x8, 0x0, 0x0, 0xc0a46b8514ba11a9, 0x3ab54f4fc583, 0x1094e40)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f fp=0xc002a7b820 sp=0xc002a7b800 pc=0x570ecf
github.com/segmentio/kafka-go.(*Conn).peekResponseSizeAndID(0xc0021f63c0, 0xccf858, 0xc001960010, 0xc0a46b8514ba11a9)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/conn.go:1251 +0x3e fp=0xc002a7b868 sp=0xc002a7b820 pc=0x6eeebe
github.com/segmentio/kafka-go.(*Conn).waitResponse(0xc0021f63c0, 0xc0021f64f0, 0xc000000007, 0x7, 0x0, 0x0, 0x0, 0x0, 0xcbea20, 0xc000e64240)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/conn.go:1342 +0xad fp=0xc002a7b8f0 sp=0xc002a7b868 pc=0x6ef3ad
github.com/segmentio/kafka-go.(*Conn).ReadBatchWith(0xc0021f63c0, 0x1, 0xf4240, 0x1094e00, 0x0, 0x3ab54f4fc583)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/conn.go:839 +0x83b fp=0xc002a7bad8 sp=0xc002a7b8f0 pc=0x6ed45b
github.com/segmentio/kafka-go.(*reader).read(0xc002a7bed8, 0xcca378, 0xc00253b100, 0x11107, 0xc0021f63c0, 0x11107, 0xcbea20, 0xc0001200f0)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/reader.go:1467 +0x125 fp=0xc002a7bd58 sp=0xc002a7bad8 pc=0x7100a5
github.com/segmentio/kafka-go.(*reader).run(0xc002a7bed8, 0xcca378, 0xc00253b100, 0x11107)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/reader.go:1310 +0x2b2 fp=0xc002a7beb0 sp=0xc002a7bd58 pc=0x70eff2
github.com/segmentio/kafka-go.(*Reader).start.func1(0xc000964e00, 0xcca378, 0xc00253b100, 0xc001b4225d, 0xb, 0x1, 0x110a3, 0xc000964f38)
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/reader.go:1211 +0x1d8 fp=0xc002a7bfa0 sp=0xc002a7beb0 pc=0x728418
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc002a7bfa8 sp=0xc002a7bfa0 pc=0x470cc1
created by github.com/segmentio/kafka-go.(*Reader).start
	/root/go/pkg/mod/github.com/segmentio/kafka-go@v0.4.31/reader.go:1191 +0x1a5
```

Our application run under k8s, only one pod crash. 

I'm not sure the crash whether came from kafka, would you please give me some suggestion on addressing the problem?

Best regard !

**Comment by achille-roussel** [comment]
At this point it seems like the issue is likely outside the scope of kafka-go, but I have a few follow up questions:
- Do you happen to have noticed other stack traces causing the program to crash?
- Would you be able to share a large part of the program for reproduction?
